// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package com.example.graphwebhook;

/**
 * Represents a subscription created by the application
 */
public class SubscriptionRecord {

    /**
     * The subscription ID returned by Microsoft Graph when the
     * subscription is created
     */
    public final String subscriptionId;

    /**
     * For delegated auth, this is the user's ID used to create the subscription.
     * For app-only auth, this is "APP-ONLY"
     */
    public final String userId;

    /**
     * The client state value used to create the subscription.
     * All notifications generated by this subscription MUST send this value
     */
    public final String clientState;

    public SubscriptionRecord(String subscriptionId, String userId, String clientState) {
        this.subscriptionId = subscriptionId;
        this.userId = userId;
        this.clientState = clientState;
    }
}
