// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package com.example.graphwebhook;

import java.util.Objects;
import org.springframework.lang.NonNull;

/**
 * Represents a subscription created by the application
 */
public class SubscriptionRecord {

    /**
     * The subscription ID returned by Microsoft Graph when the subscription is created
     */
    public final String subscriptionId;

    /**
     * For delegated auth, this is the user's ID used to create the subscription. For app-only auth,
     * this is "APP-ONLY"
     */
    public final String userId;

    /**
     * The client state value used to create the subscription. All notifications generated by this
     * subscription MUST send this value
     */
    public final String clientState;

    public SubscriptionRecord(@NonNull final String subscriptionId, @NonNull final String userId,
            @NonNull final String clientState) {
        this.subscriptionId = Objects.requireNonNull(subscriptionId);
        this.userId = Objects.requireNonNull(userId);
        this.clientState = Objects.requireNonNull(clientState);
    }
}
